### ISSUE TITLE
Wrong Counter with this plugin.

### ISSUE THREAD

**Issue by anethum** [fnogatz/magento2-matomo#11]
Hello,
after we migrate to magento2 and used this plugin, we have wrong visitors count.

After Migration
![image](https://cloud.githubusercontent.com/assets/1729737/23022501/7fa60ab0-f451-11e6-9cf9-d68c508e8b79.png)

Google Analytics said a other thinks.

![image](https://cloud.githubusercontent.com/assets/1729737/22978644/d1e093e0-f393-11e6-8295-16f569c703e9.png)

**Comment by henkelund** [comment]
Hi,

I'm not sure how to read the Piwik graph, there's no scale on the y-axis. Do you record fewer visits, or none at all? Could you provide more information about your setup? Like the URL to your website?

**Comment by anethum** [comment]
Sorry, I correct the picture,

**Comment by henkelund** [comment]
This error message is logged to the browser console: `_paq.push() was used but Piwik tracker was not initialized before the piwik.js file was loaded.`

This indicates to me that you're running Piwik 3, is that correct?

Piwik 3 [introduced a requirement](https://developer.piwik.org/changelog#piwik-300) of how the tracker javascript should be initialized which breaks backward compatibility with this module.

This has been fixed in the `1.3.0` branch and will be included in the next release coming soon™.
If you don't want to wait for the next release you're free to try installing the development branch (`composer require henhed/module-piwik:1.3.0.x-dev`). If you do, please let me know if that solves your issue.

**Comment by anethum** [comment]
Right I use piwik 3. Yes I will try this dev version

**Comment by anethum** [comment]
fixed with module-piwik:1.3.0.x-dev

**Comment by henkelund** [comment]
Great, thank you for the feedback.
